baseURL = "https://nannafudge.github.io/"
title = "Nanna's Fudge - Software Blog"
languageCode = "en-us"
theme = "hello-friend-ng"

paginate = 10
rssLimit  = 10
disableRSS = false

defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true

staticDir = ["static"]

[author]
  name = "nannafudge"

[params]
  dateform = "Jan 2, 2006"
  dateformShort = "Jan 2"
  dateformNum = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  # Subtitle for home
  homeSubtitle = "Classic recipes for effective software development"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = true

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "Personal blog about Computer Science and Cryptography"
  keywords = "software, software design, software architecture, computer science, comp-sci, cryptography, mathematics, crypto, math"
  images = [""]

  customCSS = ["/style.css"]

[permalinks]
  categories = "/blog/categories/:slug"
  tags = "/blog/tags/:slug"

[params.footer]
  trademark = true
  rss = true
  copyright = true
  author = true

[[params.social]]
  name = "twitter"
  url  = "https://twitter.com/apeth1111"
[[params.social]]
  name = "github"
  url  = "https://github.com/nannafudge"

[languages]
  [languages.en]
    title = "Nanna's Fudge"
    subtitle = "Classic recipes for effective software development"
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'

[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog"